apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - image: postgres_db
      imagePullPolicy: Never
      name: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "rahul"
        - name: POSTGRES_PASSWORD
          value: "wwe"
        - name: POSTGRES_DB
          value: "rahul"
